### ISSUE TITLE
Cannot import name modelform_factory

### ISSUE THREAD

**Issue by dethpickle** [Chris7/djangui#10]
Taking your previous advice about blowing out the migration that ships in the project for now, I was able to build new migrations and mirgrate them.  Now I'm getting this on the rest of my website - not pulling up djangui pages, but it's discovering into them when loading everything.

```
ImportError at /
cannot import name modelform_factory
Request Method: GET
Request URL:    http://....:8000/
Django Version: 1.7
Exception Type: ImportError
Exception Value:    
cannot import name modelform_factory
Exception Location: /home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/djangui/views/authentication.py in <module>, line 6
```

Chasing modelform_factory down in the Django docs pointed to https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#modelforms-factory in both 1.8 and 1.7.  This says it's located in `django.forms.models`, not `django.forms`.

I've seen other threads on StackOverflow talking about [similar issues](http://stackoverflow.com/questions/12355293/django-cannot-import-name-formset-factory) and usually attributing it to PyCharm, but if it's an editor problem, how can it possibly work?  You have a working site...  

So, I changed: _djangui/views/authentication.py_

from:  `django.forms import modelform_factory`
to: `django.forms.models import modelform_factory`

Now the rest of my site is back up.  Though I'm still not to the point where I have a working djangui... though it seems like progress.  
But I don't see how this could have been a good change.  How could you not have been having a problem with this?

**Comment by Chris7** [comment]
I made a lot of fixes for Django 1.6/1.7 compatibility. I was developing with Django 1.8 so it went un-noticed (pycharm as well, and I didn't think they would move that between versions). I just pushed a few changes that should cover 1.6/1.7. Sorry for the inconvenience, but thanks for the report :). If you install from master here you should have them.

**Comment by dethpickle** [comment]
Don't apologize, the project has amazing potential.  Thanks so much for sharing.
I'm just baffled how it can work for you when it looks like the import is also broken for 1.8 according to the docs...  I'm slowly getting there.  This could be very useful for me!

**Comment by Chris7** [comment]
You're correct, I'm going to fix that import. It is probably imported in .forms for something else so I'm picking up that reference.

**Comment by Chris7** [comment]
It should be fixed now, with the compatibility code put in with the last commit. It just emphasizes my need to get travis/tox setup to catch these things.

**Comment by dethpickle** [comment]
Confirmed your current master resolves this issue.
