### ISSUE TITLE
djangui base.html being overloaded by existing django project

### ISSUE THREAD

**Issue by dethpickle** [Chris7/djangui#12]
Perhaps through ineptitude on my part, there is an order of precedence issue where my wider site `base.html` is winning out over the djangui project base.html as referenced in three locations.

I'm under the assumption that django discovers in ever-expanding circles, but it seems to leap right to my site-wide template base.html every time.  

I've made it past this and now have a fully working djangui (yay!) site by renaming the djangui base.html to djangui_base.html and changing the three references to it here:
![djangui base html](https://cloud.githubusercontent.com/assets/3790742/7904920/97c54ffc-07c2-11e5-8e80-66859ee30e74.png)

If you suspect the order of precedence issue is entirely mine, please let me know and I'll close the issue and go figure it out.  Otherwise, just letting you know.

**Comment by Chris7** [comment]
Thanks, I thought this may be the issue. I need to put everything in a
djangui folder to give it some namespacing.

**Comment by Chris7** [comment]
I put the templates in a djangui folder, which will allow you to override them if you wish with a templates/djangui/xxx.html -- and also not be so easily overridden by your own base templates.

Thanks for your persistence with this project, you really helped catch the bugs remaining for integration with existing Django projects.

**Comment by dethpickle** [comment]
I've installed off the latest master here and confirmed the templates are now behaving.  I'll close this and thanks!

I am having one major remaining issue regarding the output files, which I think is still in the vein of _integration with existing projects_.  I'll get that submitted when I get a chance between work stuff.  Everything is being created, but not in the correct places and the URLs aren't matching the locations.  I believe it may come down to what I might boldly call missing configuration parameters.  I'll write it up when I get a chance. 
And then a minor argparse curiosity.  I think I'm using boolean in a nonstandard way. :-)
All in all, like sandman, this is looking pretty fricken cool.  Thanks for putting the time into this.

**Comment by Chris7** [comment]
Good to hear :). If you let me know your setup and where things are ending up I can maybe point you in the right direction. I only attempted to integrate this to a small set of existing projects, so I probably haven't covered every nuance to it.
