### ISSUE TITLE
Where is djanguify.py?

### ISSUE THREAD

**Issue by CatherineH** [Chris7/djangui#13]
running pip install django-djangui does not copy the djanguify.py script into my computer... I'm guessing there's a step missing in the installation section of the documentation?

**Comment by Chris7** [comment]
Can you post your machine specs? Here's my output from using pip:
mkvirtualenv djtesta
pip install django-djangui
which djanguify.py
/home/chris/Envs/djtesta/bin/djanguify.py

So djanguify is installed to the bin dir for python on my distribution (Ubuntu 14.04), and is packaged in setup.py via this:
scripts=['scripts/djanguify.py'],

**Comment by Chris7** [comment]
I'm guessing you were running windows, which this problem was just fixed. The new command is 'djanguify' instead of 'djanguify.py'. Closing this in a bit otherwise.
