### ISSUE TITLE
Output file name issue - truncating first character of path

### ISSUE THREAD

**Issue by dethpickle** [Chris7/djangui#15]
Prior to the 0d0696c build, I was getting absolute paths for all of my output files.  With this latest build it's almost right now.  They're relative paths, but are missing the first character of djangui_files.
![napkin 4 06-01-15 10 17 58 am](https://cloud.githubusercontent.com/assets/3790742/7918614/7ec178c0-0847-11e5-8c29-6a306b3e52d4.png)
![napkin 5 06-01-15 10 20 46 am](https://cloud.githubusercontent.com/assets/3790742/7918709/42634cc2-0848-11e5-8c66-5070eb757cb7.png)
If I take those broken urls in my browser and add in the missing 'd' manually, the images show up.  Sooo close.

**Comment by Chris7** [comment]
It's actually not that commit -- you'll notice you are missing the leading / from the filename with /home. That was put in to prevent double slashes in the url. It's just broken on your setup (I have no idea why it's not causing an error on mine -- can you tell me your MEDIA_ROOT?)

In backend/utils.py you will see this code on line 347:
`dj_file.filepath.name = filepath[filepath.find(settings.MEDIA_ROOT)+len(settings.MEDIA_ROOT)+1:]`

I can't get this to replicate your problem, but I think if you change it to:
`dj_file.filepath.name = filepath[filepath.find(settings.MEDIA_ROOT)+len(settings.MEDIA_ROOT):].lstrip('/')`

It will work correctly. If so, I'll update with that.

**Comment by dethpickle** [comment]
Ewww... you're right.  I did just jimmie my MEDIA_ROOT so it'd display in DEBUG.  I wouldn't have expected that to affect it on the file creation side, just the display side.

Prior, it was creating files in my BASE_DIR.  Now it's making them in the media folder, at least...  I'll tear it apart when I get back to my machine tonight.  Thanks for the clue!

**Comment by dethpickle** [comment]
I think this was all me.  I wiped my added scripted, blew out the db records and re-added and it's all working fine now.

**Comment by Chris7** [comment]
Thanks for your diligence. If possible, could I get your MEDIA_ROOT so I can see if I can prevent any issues with that in the future? My instincts tell me the +1 in my string manipulation will lead to trouble.

**Comment by Chris7** [comment]
I managed to replicate it!

MEDIA_ROOT = os.path.join(BASE_DIR, 'user_uploads/')

I'm guessing you had a trailing slash on your MEDIA_ROOT?

**Comment by dethpickle** [comment]
Initially I had nothing for MEDIA_ROOT at all.  It's a purely internal website run as a tool for me.  It's perpetually run in DEBUG = True.  I've just never had the need for `media` yet, thought I do use:

``` python
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
STATIC_URL = '/static/'
```

So, what I added when I thought your new build made the difference, was:

``` python
MEDIA_ROOT = '/home/myhomedir/tsutilweb/media'
MEDIA_URL = '/media/'
```

and then to `urls.py` from [here](http://stackoverflow.com/questions/5517950/django-media-url-and-media-root)

``` python
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
```

I see you just added the thing about the trailing slash.  Almost certainly I had a trailing slash because I would have been modeling it off the `/static/` and `/media/` that were right near it.  What would have possessed me to take it off is beyond me.  Except that you suggested it by noticing that ALL of my previous files were missing the first char.

Yay!
