### ISSUE TITLE
Existence of (possibly) malformed script preventing other script execution

### ISSUE THREAD

**Issue by streetmapp** [Chris7/djangui#18]
I will admit that the script causing the issue may need some adjusting of its own, but it was added without issue to djangui. I can also confirm it's proper execution on the command line as well.

However, with this offending script in the application, it prevents other working scripts from being executed as well. If I go to submit a job, the button is unresponsive and no output provided as to what's going on. 

Once I delete the script from within the admin, I am able to resume executing jobs for other working scripts.

Here's the script causing the issues.
https://gist.github.com/streetmapp/a7253a823562def05d76

**Comment by Chris7** [comment]
It's because of the 'user' field. That was being used internally, and consequentially overwritten. I need to consider a way to avoid all conflicts with the other 3 names we use for Djangui (djangui_type, job_name, job_description) in the form. Thanks for the report it's fixed on the latest master.

**Comment by Chris7** [comment]
Fixed by b55d5d2
