### ISSUE TITLE
Djanguifi.py not working on windows 8.1

### ISSUE THREAD

**Issue by lapsed-pacifist** [Chris7/djangui#20]
The command `djanguify.py -p ProjectName` results in 

```
usage: djanguify.py [-h] -p PROJECT
djanguify.py: error: argument -p/--project is required
```

even when I use the absolute path of the file: `python C:\Anaconda\Scripts\djanguify.py -p ProjectName`, it errors:

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\djanguify.py", line 89, in <module>
    sys.exit(main())
  File "C:\Anaconda\Scripts\djanguify.py", line 29, in main
    subprocess.call(['django-admin.py', 'startproject', project_name], env=env)
  File "C:\Anaconda\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

So I tried replacing `['django-admin.py', 'startproject', project_name]` with `['python', 'django-admin.py', 'startproject', project_name]`. This results in:

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\djanguify.py", line 89, in <module>
    sys.exit(main())
  File "C:\Anaconda\Scripts\djanguify.py", line 69, in main
    with open(to_name, 'wb') as new_file:
IOError: [Errno 2] No such file or directory: 'D:\\Repositories\\TestServer\\ProjectName\\Proje
ctName\\.\\djangui_celery_app.py'
```

I'm not sure where to go from here

**Comment by Chris7** [comment]
Hey @lapsed-pacifist,

Thanks for the report. I believe it is related to this issue here:
http://stackoverflow.com/questions/912830/using-subprocess-to-run-python-script-on-windows

Could you replace it with the file here:
https://gist.github.com/Chris7/44b4ec8c00e4426db13b

and let me know if it works? I don't have Windows 8.1 locally and travis doesn't support Windows at the moment.

**Comment by lapsed-pacifist** [comment]
It worked but not on the first try: I had to make a virtual environment (which I guess I should have done to begin with) and then call both python and djanguify.py with their absolute paths.

`ENV\Scripts\python.exe ENV\Scripts\djanguify.py -p ProjectName`

Not user friendly

**Comment by Chris7** [comment]
Did you try the gist script, and was that still failing? I'd like to keep with python based solutions to keep things as cross-platform as possible.

**Comment by Chris7** [comment]
I found a windows 8.1 computer and see the issue now @lapsed-pacifist. That is a pain, and is an issue with the executable rights of the script on Windows 8.1. I'll let you know when I find a resolution.

If you clone the latest from master, the other issues mentioned are resolved (with runserver). I'll note it looks like other scripts are affect though as well -- try django-admin.py, which raises a similar ImportError

**Comment by Chris7** [comment]
I believe this is resolved in the latest commit:

5830db832a4a867f6329cc1d2d91fcae2338b596

The command for projects is now just 'djanguify', since keeping the '.py' can have issues with windows registries choosing different interpreters.

Thanks for your efforts in this.

**Comment by Chris7** [comment]
Latest version on pip should cover these issues.
