### ISSUE TITLE
login does not work (Ubuntu)

### ISSUE THREAD

**Issue by magelan** [Chris7/djangui#23]
Hi,

I create a new djangui project  and it seams ok(webpage loads) but when I try to log in nothing happens. No error anywhere. Admin interface works. Created addional user, but same effect in the dangui window. 
Tried same under windows, and everthing is fine.
Any idea where I could look?

**Comment by Chris7** [comment]
Can you give me the output of the JavaScript console in whatever developer tools your browser has? The login and error messages are handled through ajax so there may be an issue in there. What version of django are you using and which browser?
