### ISSUE TITLE
AttributeError at /admin/djangui/script/add/

### ISSUE THREAD

**Issue by sauloal** [Chris7/djangui#7]
/home/assembly/.local/lib/python2.7/site-packages/djangui-0.1.0-py2.7.egg/djangui/backend/utils.py in add_djangui_script

```
                    return (False, parser.error)

 ...
```

▼ Local vars
Variable    Value
ScriptParameter     

<class 'djangui.models.core.ScriptParameter'>

parser  

<djangui.backend.argparse_specs.ArgParseNodeBuilder object at 0x7f33370a3310>

group   

u'makefile'

ScriptGroup     

<class 'djangui.models.core.ScriptGroup'>

extension   

u'.py'

Script  

<class 'djangui.models.core.Script'>

basename    

u'/home/assembly/tomato150/programs/iBrowser/vcfmerger/aux/djangui/ibrowser/ibrowser/user_uploads/djangui_scripts/gen_makefile'

ScriptParameterGroup    

<class 'djangui.models.core.ScriptParameterGroup'>

filename    

u'gen_makefile'

script  

u'/home/assembly/tomato150/programs/iBrowser/vcfmerger/aux/djangui/ibrowser/ibrowser/user_uploads/djangui_scripts/gen_makefile.py'

script_obj  

<Script: gen_makefile>

script_path     

u'/home/assembly/tomato150/programs/iBrowser/vcfmerger/aux/djangui/ibrowser/ibrowser/user_uploads/djangui_scripts/gen_makefile.py'

Request Method:     POST
Request URL:    http://127.0.0.1:8000/admin/djangui/script/add/
Django Version:     1.8.2
Exception Type:     AttributeError
Exception Value:    

'ArgParseNodeBuilder' object has no attribute 'error'

Exception Location:     /home/assembly/.local/lib/python2.7/site-packages/djangui-0.1.0-py2.7.egg/djangui/backend/utils.py in add_djangui_script, line 140
Python Executable:  /usr/bin/python
Python Version:     2.7.6

POST
Variable    Value
script_group    

u'1'

save_path   

u''

script_version  

u'0'

is_active   

u'on'

script_name     

u'gen_makefile'

script_order    

u'1'

execute_full_path   

u'on'

script_description  

u'gen_makefile'

csrfmiddlewaretoken     

u'6j8JpdRaPLMCARNvswOs8fOTKSbfC6zz'

_save   

u'Save'

**Comment by Chris7** [comment]
Ack, you installed djangui. I'll remove that package from pypi (I renamed to django-djangui to keep in django style). Install django-djangui and let me know if it's resolved.
